services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api
    container_name: telegram-bot-api
    init: true
    restart: always
    volumes:
      - data:/var/lib/telegram-bot-api
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH:  ${TELEGRAM_API_HASH}
      TELEGRAM_LOCAL: true
  archivebot:
    image: atareao/archivebot
    container_name: archivebot
    init: true
    restart: always
    environment:
      TOKEN: ${TOKEN}
      CHAT_ID: ${CHAT_ID}
      THREAD_ID: ${THREAD_ID}
      IA_ACCESS: ${IA_ACCESS}
      IA_SECRET: ${IA_SECRET}
      PODCAST_NAME: ${PODCAST_NAME}
      CREATOR_NAME: ${CREATOR_NAME}
    volumes:
      - data:/data


volumes:
  data: {}
